[files]
# Utils
"/www/subjects/names.json" = "./names.json"
"/www/script/utils/utils.py"= "./utils.py"

# Day 1
"/www/subjects/day_1-1.txt" = "./day_1_1.txt"
"/www/subjects/day_1-2.txt" = "./day_1_2.txt"
"/www/script/days/fragments/day_1-1.py" = "./day_1_1.py"
"/www/script/days/fragments/day_1-2.py" = "./day_1_2.py"
"/www/subjects/inputs/day_1.txt" = "./input_1.txt"

# Day 2
"/www/subjects/day_2-1.txt" = "./day_2_1.txt"
"/www/subjects/day_2-2.txt" = "./day_2_2.txt"
"/www/script/days/fragments/day_2-1.py" = "./day_2_1.py"
"/www/script/days/fragments/day_2-2.py" = "./day_2_2.py"
"/www/subjects/inputs/day_2.txt" = "./input_2.txt"

# Day 3
"/www/subjects/day_3-1.txt" = "./day_3_1.txt"
"/www/subjects/day_3-2.txt" = "./day_3_2.txt"
"/www/script/days/fragments/day_3-1.py" = "./day_3_1.py"
"/www/script/days/fragments/day_3-2.py" = "./day_3_2.py"
"/www/subjects/inputs/day_3.txt" = "./input_3.txt"

# Day 4
"/www/subjects/day_4-1.txt" = "./day_4_1.txt"
"/www/subjects/day_4-2.txt" = "./day_4_2.txt"
"/www/script/days/fragments/day_4-1.py" = "./day_4_1.py"
"/www/script/days/fragments/day_4-2.py" = "./day_4_2.py"
"/www/subjects/inputs/day_4.txt" = "./input_4.txt"
